import matplotlib.pyplot as p
import pandas as pd
import numpy as np
import seaborn as sns
data = pd.read_csv("Life_Expectancy.csv")
print(data.head())
print(data.info())
print(data.isnull().any())
sns.set_style("white")
sns.countplot(x = data["continent"])
p.show()
sns.set_style("dark")
sns.countplot(x = data["continent"])
p.show()
sns.set_style("whitegrid")
sns.countplot(x = data["continent"])
p.show()
sns.set_style("darkgrid")
sns.countplot(x = data["continent"])
p.show()
sns.set_style("ticks")
sns.countplot(x = data["continent"])
p.show()
sns.set_style("white")
sns.countplot(x = data["continent"])
sns.despine()
p.show()
sns.set_style("white")
sns.countplot(x = data["continent"], palette="winter")
p.show()
sns.set_style("whitegrid")
sns.countplot(x = data["continent"], color="Purple")
p.show()
sns.set_style("whitegrid")
sns.set_context("paper")
sns.countplot(x = data["continent"], color="Purple")
p.show()
sns.set_style("whitegrid")
sns.set_context("notebook")
sns.countplot(x = data["continent"], color="Purple")
p.show()
sns.set_style("whitegrid")
sns.set_context("talk")
sns.countplot(x = data["continent"], color="Purple")
p.show()
sns.set_style("whitegrid")
sns.set_context("poster")
sns.countplot(x = data["continent"], color="Purple")
p.show()
sns.set_style("whitegrid")
sns.set_context("poster")
sns.countplot(x = data["continent"], color="Purple")
p.xticks(rotation = 45)
p.show()
sns.set_context("poster", font_scale=0.8)
sns.countplot(x = data["continent"], color="Purple")
p.xticks(rotation = 45)
p.show()